### ISSUE TITLE
ros-indigo-nao-apps package: python nodes do not have the executable bit set

### ISSUE THREAD

**Issue by severin-lemaignan** [ros-naoqi/nao_robot#19]
After installing `ros-indigo-nao-apps 0.5.6-0trusty-20150227-2029-+0000`, it appears that none of the Python nodes have their executable bit set, making all launch files referencing them unusable.

For instance,
```
$ roslaunch nao_apps leds.launch 

[...]
ERROR: cannot launch node of type [nao_apps/nao_leds.py]: can't locate node [nao_leds.py] in package [nao_apps]
No processes to monitor
shutting down processing monitor...
... shutting down processing monitor complete
``` 

Manually `chmod +x` them fix the issue.

**Comment by vrabaud** [comment]
@Karsten1987 , pleae fix using http://docs.ros.org/indigo/api/catkin/html/dev_guide/generated_cmake_api.html#catkin-install-python

**Comment by kochigami** [comment]
thank you your fix, I run into same problem.
It seems you forget to send to ros/distro
https://github.com/ros/rosdistro/blob/master/indigo/distribution.yaml#L4579

**Comment by vrabaud** [comment]
my bad, done in https://github.com/ros/rosdistro/pull/8212
