### ISSUE TITLE
robot model in naoV50_generated_urdf

### ISSUE THREAD

**Issue by nlyubova** [ros-naoqi/nao_robot#22]
Is the robot model = "NaoH25V40" in nao_description/urdf/naoV50_generated_urdf/nao.urdf and .../nao_robot.urdf correct? isn't it "NaoH25V50"?

https://github.com/ros-naoqi/nao_robot/blob/master/nao_description/urdf/naoV50_generated_urdf/nao_robot.xacro#L5 

Would it be possible to release nao-description (and also romeo-description), because the robot models there are rather old?

**Comment by vrabaud** [comment]
Got fixed in https://github.com/ros-naoqi/nao_robot/commit/bf0c0fe3e897c196fe82cb46dcca9bd3d2fa65c4
