### ISSUE TITLE
r_wrist frame typo

### ISSUE THREAD

**Issue by letrend** [ros-naoqi/nao_robot#25]
There is obviously a typo in the nao_description/urdf/naoVXX_generated_urdf/nao_robot.xacro files in versions XX=32/33/40/50, causing the coordinate frame of r_gripper to have an offset in rotation.

Current length:
```
<child link="l_gripper"/>
<origin rpy="0 0 0" xyz="0.05775 0 -0.01213"/>
```

Actual length:
```
<child link="l_gripper"/>
<origin rpy="0 0 0" xyz="0.05775 0 -0.01231"/>
```
Note the -0.01231
The dimensions can be checked on [Aldebarans page](http://doc.aldebaran.com/2-1/family/nao_h25/links_h25.html)

**Comment by vrabaud** [comment]
@suryaambrose, @lsouchet, please confirm / infirm.

**Comment by keulYSMB** [comment]
Please note that the V32 values are fine but 33/40/50 have the same typo.

**Comment by sbarthelemy** [comment]
I confirm the typo, I found the same inside aldebaran's library from which the urdf files are generated.
Now that I fixed it there, I suppose generating the urdf files again should propagate the fix to ros.

**Comment by vrabaud** [comment]
@sbarthelemy thx. Can you please send me the newly generated URDFs so that I fix that bug ? Thx. Otherwise, you can make a PR yourself using those instructions: https://github.com/ros-naoqi/naoqi_bridge/blob/master/naoqi_tools/scripts/README_generate_urdf.py.rst

**Comment by vrabaud** [comment]
btw, @letrend , how did you find that bug ? did it impact any of your experiments ?

**Comment by letrend** [comment]
@vrabaud 
jup, made transformations from gripper to torso frame impossible. 
at first this seemed to solve our issues, but we noticed that the coordinate frame of the right gripper was still weiredly twisted. So there might still be something wrong about the coordinat frames. we couldnt figure out what, however.
eventually we used visual tracking of the endeffector to compensate for this.
